import { DEFAULT_OFFER_COOLDOWN_DAYS } from '@/lib/offers'

export const RESTAURANT_REDEEM_COOLDOWN_DAYS = DEFAULT_OFFER_COOLDOWN_DAYS

export const RESTAURANT_REDEEM_COOLDOWN_TEXT =
  `Не чаще 1 раза в ${RESTAURANT_REDEEM_COOLDOWN_DAYS} дней на один ресторан`
